const zone2ProjectsSeedData = [
  {
    categoryId: 'projects',
    slug: 'votezone',
    name: 'Srivarshini G',
    title: 'VoteZone',
    year: '3rd Year',
    programme: 'BE CSE',
    class: '',
    description: 'A secure, full-stack platform for transparent, one-vote-per-user college election voting and result tallying.',
    problemStatement: 'Manual or semi-digital college election processes are prone to duplicate voting, tallying errors, and lack of transparency in candidate management.',
    solutionOverview: 'VoteZone is a full-stack voting platform built with FastAPI, React.js, and PostgreSQL, exposing secure REST APIs for candidate management, vote casting, and result tallying, with role-based access control that enforces one-vote-per-user integrity.',
    githubLink: 'https://github.com/varshinii15/VoteZone.git'
  },
  {
    categoryId: 'projects',
    slug: 'debugiq',
    name: 'Dharaneesh S L',
    title: 'DebugIQ — AI-Assisted Simulation Log Analysis Platform',
    year: '3rd Year',
    programme: 'BE CSE',
    class: 'G1',
    description: 'An AI-powered platform that analyzes simulation logs to detect and explain failures faster.',
    problemStatement: 'Simulation and system logs generate massive volumes of data, making it difficult for engineers to manually identify failures and understand recurring issues.',
    solutionOverview: 'DebugIQ is an AI-powered log intelligence platform that analyzes simulation logs, automatically clusters similar failures, and surfaces explainable, severity-based insights to speed up root-cause diagnosis.',
    githubLink: 'https://github.com/Dharaneeshsl/DebugIQ'
  },
  {
    categoryId: 'projects',
    slug: 'phishx',
    name: 'Dharaneesh S L',
    title: 'PhishX — Real-Time Phishing Detection & Prevention Platform',
    year: '3rd Year',
    programme: 'BE CSE',
    class: 'G1',
    description: 'An AI-powered platform providing real-time phishing detection and protection across URLs, emails, and browsers.',
    problemStatement: 'Phishing attacks increasingly span URLs, emails, and web content, leaving users without unified, real-time protection against evolving threats.',
    solutionOverview: 'PhishX is an AI-powered, full-stack platform that detects and prevents phishing across URLs, emails, and web content, including real-time browser-level protection for end users.',
    githubLink: 'https://github.com/Dharaneeshsl/PhishX'
  },
  {
    categoryId: 'projects',
    slug: 'instagram-clone',
    name: 'Thirukkumaran',
    title: 'Instagram Clone',
    year: '2nd Year',
    programme: 'BE CSE',
    class: 'G2',
    description: 'A React-based frontend clone of Instagram built for UI/UX and state management practice.',
    problemStatement: 'Learning modern frontend frameworks requires hands-on practice replicating real-world, complex UI/UX patterns at scale.',
    solutionOverview: 'A React-based frontend clone of Instagram, built to practice component design, state management, and responsive UI development.',
    githubLink: 'https://github.com/thirudev-web/'
  },
  {
    categoryId: 'projects',
    slug: 'fooddeliveryapp',
    name: 'Prithvi S',
    title: 'FoodDeliveryApp',
    year: '2nd Year',
    programme: 'BE CSE',
    class: 'G2',
    description: 'A MERN-stack food delivery platform with authentication, payments, and real-time order tracking.',
    problemStatement: 'Food ordering platforms must integrate authentication, secure payments, and real-time order tracking cohesively, which is challenging to build from scratch.',
    solutionOverview: 'A MERN-stack food delivery platform offering user authentication, online payment processing, and real-time order management end to end.',
    githubLink: 'https://github.com/SoloFPS/FoodDeliveryApp'
  },
  {
    categoryId: 'projects',
    slug: 'ai-powered-crowd-management',
    name: 'M Harrish',
    title: 'AI Powered Crowd Management',
    year: '2nd Year',
    programme: 'UG',
    class: 'AIML',
    description: 'An offline Edge-AI system that predicts crowd surges in real time to prevent stampedes.',
    problemStatement: 'Large public gatherings are vulnerable to sudden crowd surges and stampedes, and existing monitoring systems often lack real-time capability in low-connectivity environments.',
    solutionOverview: 'An offline Edge-AI system that predicts crowd surges in real time on-device and triggers early alerts to prevent stampedes before they happen.',
    githubLink: 'https://github.com/M-Harrish'
  },
  {
    categoryId: 'projects',
    slug: 'ai-based-canal-intelligence',
    name: 'M Harrish',
    title: 'AI-Based Canal Intelligence for Water Management',
    year: '2nd Year',
    programme: 'UG',
    class: 'AIML',
    description: 'An AI system using satellite imagery to prioritize canal desilting and irrigation maintenance.',
    problemStatement: 'Irrigation authorities often lack data-driven methods to prioritize canal desilting and maintenance, leading to inefficient use of limited resources.',
    solutionOverview: 'An AI-driven system that uses satellite imagery and simulation to identify vulnerable water canals, turning criticality mapping and desilting decisions into data-backed, cost-optimized action for maximizing irrigation impact.',
    githubLink: 'https://github.com/M-Harrish'
  },
  {
    categoryId: 'projects',
    slug: 'ebonica-daml',
    name: 'Ebonica Saleth V',
    title: 'ebonica-daml 0.2.0 : Disagreement-Aware Multi-Learning',
    year: '2nd Year',
    programme: 'PG',
    class: '',
    description: 'A Python ML library that detects ambiguous data using ensemble disagreement and adaptive retraining.',
    problemStatement: 'Machine learning models often make confident predictions on inherently ambiguous or mislabeled data, degrading real-world reliability.',
    solutionOverview: 'A production-level Python machine learning library that detects ambiguous data using ensemble disagreement and supports adaptive retraining to improve model robustness over time.',
    githubLink: 'https://pypi.org/project/ebonica-daml/'
  },
  {
    categoryId: 'projects',
    slug: 'nexus-coder',
    name: 'Santhosh Kumar M',
    title: 'Nexus-Coder',
    year: '3rd Year',
    programme: 'UG',
    class: 'G2',
    description: 'An AI-powered coding platform combining interview practice, an IDE, and progress tracking for students.',
    problemStatement: 'Junior developers preparing for technical interviews often lack company-specific practice material, an integrated coding environment, and structured progress tracking, all in one place.',
    solutionOverview: 'Nexus Coder is an AI-powered coding platform that combines company-specific interview practice, an integrated C/Python IDE, progress tracking, and intelligent hints to help juniors prepare more effectively.',
    githubLink: 'https://github.com/santi-git-prog/Nexus-Coder.git'
  },
  {
    categoryId: 'projects',
    slug: 'applyo',
    name: 'Nithish S',
    title: 'Applyo',
    year: '3rd Year',
    programme: 'UG',
    class: 'G2',
    description: 'A MERN job portal streamlining job discovery, applications, and recruiter hiring workflows.',
    problemStatement: 'Job seekers and recruiters face fragmented workflows across job discovery, applications, resume management, and hiring.',
    solutionOverview: 'A full-stack job portal built using the MERN stack that streamlines job discovery, applications, resume management, and recruiter hiring workflows through secure authentication and role-based dashboards.',
    githubLink: 'https://github.com/nithish-github07/Applyo'
  },
  {
    categoryId: 'projects',
    slug: 'adaptive-multi-agent-knowledge-framework',
    name: 'Nivetha S',
    title: 'An Adaptive Multi-Agent Framework for AI-Powered Enterprise Knowledge Preservation and Transfer',
    year: '2nd Year',
    programme: 'PG',
    class: '',
    description: 'A multi-agent AI framework that consolidates organizational knowledge for preservation and transfer.',
    problemStatement: 'Organizations often store institutional knowledge across disparate, siloed sources, making it hard for employees to retrieve accurate information or preserve knowledge when staff turnover occurs.',
    solutionOverview: "An adaptive multi-agent, AI-powered framework that collects knowledge from an organization's various sources, consolidates it, and provides that information back to the organization for preservation and transfer.",
    githubLink: 'https://github.com/Nivetha-Selvakumar/knowledge-preservation-framework-python'
  },
  {
    categoryId: 'projects',
    slug: 'qrveil',
    name: 'Vishal Ram C S',
    title: 'QRVeil',
    year: '2nd Year',
    programme: 'PG',
    class: 'AIML',
    description: 'A desktop app that hides an encrypted secret message inside an ordinary QR code.',
    problemStatement: 'Sharing sensitive information covertly and securely is difficult without drawing attention to the fact that a secret is being transmitted.',
    solutionOverview: 'A desktop application that embeds an encrypted secret message inside an ordinary-looking QR code, enabling covert, secure communication.',
    githubLink: 'https://github.com/Proxyprisoner/QRVeil.git'
  },
  {
    categoryId: 'projects',
    slug: 'expense-tracker',
    name: 'Dhanasoorya M E',
    title: 'Expense Tracker',
    year: '2nd Year',
    programme: 'UG',
    class: 'AIML',
    description: 'An app that helps users record, categorize, and analyze daily expenses for better budgeting.',
    problemStatement: 'Individuals often struggle to consistently record, categorize, and analyze their daily spending, making budget management difficult.',
    solutionOverview: 'An Expense Tracker application that helps users record, categorize, monitor, and analyze their daily expenses to manage their budget effectively.',
    githubLink: 'https://github.com/medhanasoorya2007/Expense-tracker'
  },
  {
    categoryId: 'projects',
    slug: 'applyready-ai',
    name: 'Sujith E',
    title: 'ApplyReady AI',
    year: '2nd Year',
    programme: 'UG',
    class: 'G1',
    description: 'An AI platform helping students track requirements and readiness across multiple applications.',
    problemStatement: 'Students pursuing scholarships, internships, or admissions often struggle to track eligibility requirements, manage supporting documents, and gauge readiness across multiple applications.',
    solutionOverview: 'An AI-powered platform that helps students analyze opportunities, identify requirements, manage supporting documents, and track application readiness.',
    githubLink: 'https://github.com/sujith0718-coder/ApplyReady-AI'
  },
  {
    categoryId: 'projects',
    slug: 'spoonfeeder',
    name: 'Suganth V',
    title: 'SPOONFEEDER',
    year: '3rd Year',
    programme: 'UG',
    class: 'G2',
    description: 'A structured learning platform helping students, especially arrear students, study more efficiently.',
    problemStatement: "Students, especially those with backlog/arrear subjects, often waste time searching for scattered study material instead of learning efficiently, and traditional reteaching by faculty doesn't scale.",
    solutionOverview: "A structured learning platform that organizes content to save students' study time and supports arrear students, so they can catch up without instructors having to reteach everything.",
    githubLink: 'spoonfeeders.vercel.app (GitHub link private)'
  },
  {
    categoryId: 'projects',
    slug: 'drishti',
    name: 'Sahaana Mahalakshme V',
    title: 'DRISHTI - Dynamic Real-time Intelligence for Situation & Traffic Insight',
    year: '3rd Year',
    programme: 'UG',
    class: 'G1',
    description: 'A real-time traffic intelligence platform using AI for predictive incident analysis and response.',
    problemStatement: 'Urban traffic management systems often react to incidents after they occur rather than anticipating them, leading to delayed responses and congestion.',
    solutionOverview: 'A real-time traffic intelligence platform leveraging AI for predictive incident analysis and faster response coordination.',
    githubLink: 'https://github.com/sahaanamahalakshme/gridlock.git'
  },
  {
    categoryId: 'projects',
    slug: 'sugarcane-leaf-disease-diagnosis',
    name: 'Dhana Sree R',
    title: 'An Explainable Deep Learning Approach for Sugarcane Leaf Disease Diagnosis',
    year: '2nd Year',
    programme: 'PG',
    class: '',
    description: 'An explainable deep learning system for diagnosing sugarcane leaf disease severity and spread.',
    problemStatement: 'Farmers and agricultural experts often lack fast, accurate, and interpretable tools to diagnose sugarcane leaf diseases and assess their severity and spread, delaying corrective action.',
    solutionOverview: 'An explainable deep learning system for sugarcane leaf disease prediction and classification, including disease severity and spread calculation, to support timely intervention.',
    githubLink: ''
  },
  {
    categoryId: 'projects',
    slug: 'data-visualisation',
    name: 'Jeevan Mishael P',
    title: 'Data Visualisation',
    year: '2nd Year',
    programme: 'UG',
    class: 'G2',
    description: 'An application that recommends the best graphical representation for a given dataset.',
    problemStatement: 'Choosing the most effective graphical representation for a given dataset is often a manual, expertise-dependent task for non-technical users.',
    solutionOverview: 'An application that generates and recommends the best graphical representation for any given dataset.',
    githubLink: 'https://share.google/ESin3c7ZCmGDvx1Dh'
  }
];

module.exports = zone2ProjectsSeedData;